---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: 'test/fixtures/environments'

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[sauron::default]
    attributes:
